# Generated by Django 5.1.4 on 2025-01-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
