# Generated by Django 5.1.4 on 2025-01-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_rename_user_userprofile_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
