# Generated by Django 5.1.4 on 2025-01-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='nummer',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(to='join_api.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioIcon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.TextField(blank=True),
        ),
    ]
