# Generated by Django 5.1.4 on 2025-01-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0002_user_alter_contact_nummer_alter_task_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10),
        ),
    ]
