# Generated by Django 5.1.4 on 2025-01-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0004_remove_contact_color_alter_task_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(to='join_api.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], max_length=10),
        ),
    ]
