# Generated by Django 5.1.4 on 2025-01-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0005_alter_task_contacts_alter_task_prio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='phases',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioIcon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
