# Generated by Django 5.1.4 on 2025-01-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0006_alter_task_category_alter_task_phases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nummer',
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
