# Generated by Django 5.1.4 on 2025-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0007_remove_contact_nummer_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
