# Generated by Django 5.1.4 on 2025-01-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0008_alter_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='phone_number',
        ),
    ]
