# Generated by Django 5.1.4 on 2025-01-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0012_alter_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prioIcon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
