# Generated by Django 5.1.4 on 2025-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0013_task_prioicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
