# Generated by Django 5.1.4 on 2025-01-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0014_contact_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(related_name='tasks', to='join_api.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='phases',
            field=models.CharField(default='To Do', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(default=list),
        ),
    ]
