# Generated by Django 5.1.4 on 2025-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0015_alter_task_category_alter_task_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='join_api.contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='phases',
            field=models.CharField(default='To Do', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
