# Generated by Django 5.1.4 on 2025-01-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0017_alter_task_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
    ]
