# Generated by Django 5.1.4 on 2025-01-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0018_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(choices=[('#3380FF', '#3380FF'), ('#1d6331', '#1d6331'), ('#FFEA33', '#FFEA33'), ('#FF5733', '#FF5733'), ('#7A33FF', '#7A33FF'), ('#FF33C1', '#FF33C1'), ('#33E6FF', '#33E6FF'), ('#FF33A2', '#FF33A2'), ('#33FFF1', '#33FFF1')], max_length=20, null=True),
        ),
    ]
