# Generated by Django 5.1.4 on 2025-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0019_alter_contact_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
