# Generated by Django 5.1.4 on 2025-01-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0021_remove_contact_color_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
