# Generated by Django 5.1.4 on 2025-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0023_remove_task_subtasks_task_category_color_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phases',
            field=models.CharField(default='To do', max_length=50),
        ),
    ]
