# Generated by Django 5.1.4 on 2025-01-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0024_alter_task_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phases',
            field=models.CharField(default='To Do', max_length=50),
        ),
    ]
