# Generated by Django 5.1.4 on 2025-02-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0026_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
